apiVersion: v1
kind: Secret
metadata:
  name: connections-secret
stringData:
  "postgres_host": "{{ .Release.Name }}-postgresql"
  "postgres_password": "{{ .Values.postgresPassword }}"
  "rabbitMq_host": "{{ .Release.Name }}-rabbitmq"
  "rabbitMq_user": "{{ .Values.rabbitMqUser }}"
  "rabbitMq_password": "{{ .Values.rabbitMqPassword }}"