apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-order-service-{{ .Release.Revision }}
  labels:
    {{- include "stream-processing.labels" . | nindent 4 }}
    app: {{ .Release.Name }}-order-service-{{ .Release.Revision }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-order-service-{{ .Release.Revision }}
  template:
    metadata:
      name: {{ .Release.Name }}-order-service-{{ .Release.Revision }}
      labels:
        app: {{ .Release.Name }}-order-service-{{ .Release.Revision }}
    spec:
      containers:
        - env:
            - name: "POSTGRES_HOST"
              valueFrom:
                secretKeyRef:
                  key: "postgres_host"
                  name: "connections-secret"
            - name: "RABBITMQ_HOST"
              valueFrom:
                secretKeyRef:
                  key: "rabbitMq_host"
                  name: "connections-secret"
            - name: "POSTGRES_PASSWORD"
              valueFrom:
                secretKeyRef:
                  key: "postgres_password"
                  name: "connections-secret"
            - name: "RABBITMQ_USER"
              valueFrom:
                secretKeyRef:
                  key: "rabbitMq_user"
                  name: "connections-secret"
            - name: "RABBITMQ_PASSWORD"
              valueFrom:
                secretKeyRef:
                  key: "rabbitMq_password"
                  name: "connections-secret"
          name: {{ .Release.Name }}-order-service-{{ .Release.Revision }}
          image: kuzindiman/sp_order_service:latest
          imagePullPolicy: Always
      restartPolicy: Always
      